version: '3.3'
services:
    traefik:
        image: "traefik:latest"
        container_name: "traefik"
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8080:8080"
        networks:
            - default
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"

    grocerie_front:
        container_name: grocerie_front
        image: grocerie/nuxt
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.grocerie_front.rule=Host(`grocerie.localhost`)"
            - "traefik.port=3000"
        volumes:
            - ../:/app
            - /app/node_modules
        ports:
            - 3000:3000
        command: "yarn"
        networks:
            - default
        restart: always

networks:
    default:
        driver: bridge
